ebook_extensions = [
    ['pdf', 'Adobe Portable document format'],
    ['epub', 'Open Publication structure e-book'],
    ['.djvu', 'To be populated.'],
    ['mobi', 'Mobipocket eBook format'],

    ['azn', 'Amazon Kindle newspaper data'],
    ['azw', 'Amazon Kindle eBook format'],
    ['azw1', 'Amazon Kindle Topaz e-book'],
    ['azw3', 'Amazon Kindle eBook'],
    ['azw4', 'Amazon Kindle Print Replica e-book'],
    ['azw6', 'Amazon Kindle eBook'],

    ['cbcx', 'Comic Book Creator comic book save file format'],
    ['cbds', 'Comic Book DS data'],
    ['cbmv', 'Comic Book Millennium collection data'],
    ['cbr', 'Comic Book Archive file or ComicBook Reader e-book'],
    ['cbt', 'CDisplay TAR Comic book file'],
    ['cbz', 'Comic Book Archive file or ComicBook Reader e-book'],

    ['aeh', 'Archos ebook file'],
    ['apnx', 'Amazon Kindle ebook index'],
    ['ava', 'AvaaBook e-book'],
    ['bdb2', 'Skillpipe course data file'],
    ['bek', 'Shanda Bambook e-book'],
    ['bfl', 'yBook e-book'],
    ['bkk', 'BookBuddi e-book'],
    ['bpnueb', 'Payame Noor University (PNU) e-book'],
    ['brn', 'yBook compiled eBook'],
    ['cb7', 'CDisplay 7-Zip comic book'],
    ['cba', 'CDisplay ACE Comic book'],
    ['cbc', 'Sony Portable Reader comic e-book'],
    ['ceb', 'Apabi e-book'],
    ['cebx', 'Apabi e-Book data'],
    ['chmprj', 'Abee CHM Maker HTML archive'],
    ['cl2arc', 'Comic Life 2 document archive'],
    ['cl2doc', 'Comic Life 2 document'],
    ['comictpl', 'Comic Life template'],
    ['csd', 'CSD Reader Compact Shared Document'],
    ['dbk', 'DocBook source data'],
    ['dfm', 'Help & Manual eBook template'],
    ['dnl', 'DNAML e-Book data'],
    ['eba', 'EBA ebook format'],
    ['ebaml', 'EBA ebook format'],
    ['ebk', 'eBook Pro e-book file'],
    ['ebk2', 'E-book format'],
    ['ebo', 'Microsoft Reader eBook Format'],
    ['ebx', 'Electronic Book exchange e-book'],
    ['edt', 'Adobe Ebook download settings'],
    ['fb2', 'FictionBook e-Book'],
    ['fb3', 'FictionBook3 ebook'],
    ['fbz', 'FictionBook e-book (compressed)'],
    ['fub', 'Franklin e-book format'],
    ['gpf', 'Ganaxaâ€™s Publishing e-book'],
    ['gpx', 'Ganaxaâ€™s Publishing DRM protected ebook file'],
    ['hsb', 'HandStory Suite eBook file'],
    ['html0', 'Book Designer e-book file'],
    ['htmlz', 'Zipped HTML document or e-book'],
    ['htxt', 'Hanvon WISEreader e-book file'],
    ['htz4', 'HyperMaker publication'],
    ['iba', 'iBooks Author e-book'],
    ['ibook', 'iBooks e-book data'],
    ['ibooks', 'iBooks e-book'],
    ['imp', 'IMP e-book format'],
    ['jwpub', 'Bible study publication format'],
    ['kf8', 'Amazon Kindle Format 8'],
    ['kml', 'Hiebook e-Book'],
    ['lbxcol', 'Libronix DLS resource collection data'],
    ['lbxoeb', 'Libronix DLS resource'],
    ['lit', 'Microsoft Reader eBook'],
    ['lrf', 'BBeB ebook'],
    ['lrs', 'BBeB ebook source file'],
    ['lrt', 'e-Book data'],
    ['lrx', 'BBeB ebook file'],
    ['luci', 'Amazon Kindle Fire mobi ebook container'],
    ['mart', 'Martview e-book data'],
    ['mbp1', 'Kindle Touch annotation data'],
    ['meb', 'Open e-book data'],
    ['mga', 'Manga comics document file'],
    ['mpub', 'Mobile optimized ePub ebook'],
    ['nat', 'Natata eBook file'],
    ['oeb', 'Open eBook format'],
    ['opf', 'Open Packaging Format'],
    ['orb', 'Original eBook Reader e-book'],
    ['original_epub', 'EPUB e-book backup'],
    ['original_mobi', 'MOBI ebook backup'],
    ['pdb', 'Palm OS database or e-book'],
    ['pdg', 'Chinamaxx/SSreader digital book'],
    ['phl', 'Amazon Kindle popular highlights data'],
    ['pkg', 'file icon pkg Apple Newton e-book'],
    ['pml', 'Palm Markup Language source code'],
    ['pmlz', 'e-Book'],
    ['pobi', 'Kindle store magazine e-book'],
    ['prc', 'Mobipocket eBook'],
    ['prc', 'Palm OS resource or e-book'],
    ['qmk', 'YanCEyDesktop bookmark data'],
    ['rb', 'RocketEdition eBook file'],
    ['sbrz', 'Sky Ebook Reader e-book'],
    ['seb', 'Franklin eBookMan e-book'],
    ['sgf', 'Sigil e-book'],
    ['snb', 'Shanda Bambook eBook file'],
    ['stk', 'STAReBOOK ebook file'],
    ['tcr', 'TCR eBook file'],
    ['tk3', 'TK3 multimedia eBook file'],
    ['tpnueb', 'Payame Noor University e-book'],
    ['tpz', 'Amazon Kindle Topaz e-book'],
    ['tr', 'TomeRaider e-book'],
    ['tr2', 'TomeRaider eBook'],
    ['tr3', 'TomeRaider eBook data'],
    ['txt7', 'e-Book'],
    ['txtc', 'e-Book'],
    ['txtr', 'eBook'],
    ['txtz', 'eBook'],
    ['ubk', 'Embiid e-book'],
    ['umd', 'UMD mobile e-book'],
    ['vbk', 'VitalSource Bookshelf VitalBook format eBook'],
    ['vellum', 'Vellum e-book project'],
    ['wbp', 'Webshots picture collection'],
    ['webz', 'Web Format compressed eBook file'],
    ['wmga', 'Web Manga comics document file'],
    ['wolf', 'WOLF document'],
    ['xeb', 'Apabi eBook format'],
    ['xmdf', 'XMDF e-book'],
    ['ybhtm', 'yBook HTML document'],
    ['ybk', 'YanCEyWare eBook format'],
    ['ybrar', 'yBook e-book'],
    ['ybrtf', 'Ybook ebook file'],
    ['ybtxt', 'Ybook ebook file'],
    ['zna', 'Zinio Digital Publication annotation'],
    ['zno', 'Zinio reader magazine data']
]

ebook_extensions_slim = [
    'azw3',
    'azw6',
    'azw4',
    'azw',
    'apnx',
    'azw1',
    'ava',
    'azn',
    'aeh',
    'bdb2',
    'bfl',
    'bek',
    'bkk',
    'bpnueb',
    'brn',
    'cbr',
    'cbz',
    'ceb',
    'cbt',
    'cbc',
    'cebx',
    'cb7',
    'cl2arc',
    'csd',
    'comictpl',
    'cba',
    'cbds',
    'cbcx',
    'chmprj',
    'cl2doc',
    'cbmv',
    'dnl',
    'dbk',
    'dfm',
    'epub',
    'edt',
    'ebo',
    'ebk',
    'ebk2',
    'eba',
    'ebaml',
    'ebx',
    'fb2',
    'fub',
    'fb3',
    'fbz',
    'gpf',
    'gpx',
    'htmlz',
    'htxt',
    'htz4',
    'html0',
    'hsb',
    'ibooks',
    'iba',
    'ibook',
    'imp',
    'jwpub',
    'kf8',
    'kml',
    'lit',
    'luci',
    'lbxoeb',
    'lrx',
    'lbxcol',
    'lrf',
    'lrt',
    'lrs',
    'mobi',
    'mbp1',
    'mpub',
    'mart',
    'mga',
    'meb',
    'nat',
    'opf',
    'orb',
    'original_epub',
    'original_mobi',
    'oeb',
    'pdf',
    'pdg',
    'pdb',
    'prc',
    'prc',
    'pobi',
    'pkg',
    'pmlz',
    'phl',
    'pml',
    'qmk',
    'rb',
    'seb',
    'snb',
    'sbrz',
    'stk',
    'sgf',
    'tr',
    'tpz',
    'txtz',
    'txt7',
    'tk3',
    'txtc',
    'tcr',
    'tr3',
    'txtr',
    'tpnueb',
    'tr2',
    'umd',
    'ubk',
    'vbk',
    'vellum',
    'wolf',
    'wbp',
    'webz',
    'wmga',
    'xmdf',
    'xeb',
    'ybhtm',
    'ybk',
    'ybrar',
    'ybtxt',
    'ybrtf',
    'zno',
    'zna'
]
