
def display_help():
    print('')
    print('')
    print('[  LibGenesis Downloader   ]')
    print('')
    print('-k         Keyword       Specify a search string.')
    print('-p         Page          Specify a page to start downloading from (optional). -p 1')
    print('-P         Path          Specify save path (optional).')
    print('-max       Max           Specify a page to end downloading (optional). -max 3')
    print('--no-mem   No Memory     Do not use books_saved.txt when ascertaining if file will be downloaded.')
    print('-v         Verbosity     Increase verbosity.')
    print('-h         Help          Displays this help message.')
    print('')
    print('Developed and written by Benjamin Jack Cullen.')
    print('')
    print('')
